#!/usr/bin/env python3
"""contracts 双端生成器：schemas/*.json → generated/py/events.py + generated/ts/events.ts。

用法：
  python gen.py          # 生成
  python gen.py --check  # 校验生成物与 schema 一致（CI 用，不一致退出码 1）

仅支持契约用到的 JSON Schema 子集：object/properties/required/additionalProperties、
$ref(#/$defs/X)、enum、const、array/items、string/integer/number/boolean。
任何一边手改生成物 = --check 失败。
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SCHEMA_DIR = HERE.parent / "schemas"
OUT_PY = HERE.parent / "generated" / "py" / "events.py"
OUT_TS = HERE.parent / "generated" / "ts" / "events.ts"

HEADER = "# Code generated by packages/contracts/scripts/gen.py. DO NOT EDIT.\n"
HEADER_TS = "// Code generated by packages/contracts/scripts/gen.py. DO NOT EDIT.\n"


def load_schemas() -> dict[str, dict]:
    defs: dict[str, dict] = {}
    for path in sorted(SCHEMA_DIR.glob("*.json")):
        doc = json.loads(path.read_text(encoding="utf-8"))
        for name, sub in doc.get("$defs", {}).items():
            if name in defs:
                raise SystemExit(f"跨源 type 重名: {name} ({path.name})")
            defs[name] = sub
    return defs


def py_type(node: dict, defs: dict[str, dict]) -> str:
    if "$ref" in node:
        return node["$ref"].split("/")[-1]
    if "const" in node:
        return f"Literal[{node['const']!r}]"
    if "enum" in node:
        vals = ", ".join(repr(v) for v in node["enum"])
        return f"Literal[{vals}]"
    t = node.get("type")
    if t == "string":
        return "str"
    if t == "integer":
        return "int"
    if t == "number":
        return "float"
    if t == "boolean":
        return "bool"
    if t == "array":
        return f"list[{py_type(node.get('items', {}), defs)}]"
    if t == "object":
        if "properties" in node:
            return "dict[str, Any]"
        return "dict[str, Any]"
    return "Any"


def ts_type(node: dict, defs: dict[str, dict]) -> str:
    if "$ref" in node:
        return node["$ref"].split("/")[-1]
    if "const" in node:
        return json.dumps(node["const"])
    if "enum" in node:
        return " | ".join(json.dumps(v) for v in node["enum"])
    t = node.get("type")
    if t == "string":
        return "string"
    if t in ("integer", "number"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "array":
        return f"{ts_type(node.get('items', {}), defs)}[]"
    if t == "object":
        return "Record<string, unknown>"
    return "unknown"


def gen_py(defs: dict[str, dict]) -> str:
    lines = [HEADER, "from __future__ import annotations\n",
             "from typing import Any, Literal\n",
             "from pydantic import BaseModel, ConfigDict\n\n"]
    for name, node in defs.items():
        if node.get("type") != "object" or "properties" not in node:
            # 纯枚举（如 Lamp）→ 类型别名
            lines.append(f"{name} = {py_type(node, defs)}\n\n")
            continue
        required = set(node.get("required", []))
        lines.append(f"class {name}(BaseModel):\n")
        lines.append("    model_config = ConfigDict(extra='forbid')\n")
        for prop, spec in node["properties"].items():
            t = py_type(spec, defs)
            if prop in required:
                lines.append(f"    {prop}: {t}\n")
            else:
                lines.append(f"    {prop}: {t} | None = None\n")
        lines.append("\n")
    return "".join(lines)


def gen_ts(defs: dict[str, dict]) -> str:
    lines = [HEADER_TS]
    for name, node in defs.items():
        if node.get("type") != "object" or "properties" not in node:
            lines.append(f"export type {name} = {ts_type(node, defs)};\n\n")
            continue
        required = set(node.get("required", []))
        lines.append(f"export interface {name} {{\n")
        for prop, spec in node["properties"].items():
            opt = "" if prop in required else "?"
            lines.append(f"  {prop}{opt}: {ts_type(spec, defs)};\n")
        lines.append("}\n\n")
    return "".join(lines)


def main() -> int:
    defs = load_schemas()
    py, ts = gen_py(defs), gen_ts(defs)
    if "--check" in sys.argv:
        ok = (OUT_PY.exists() and OUT_PY.read_text(encoding="utf-8") == py
              and OUT_TS.exists() and OUT_TS.read_text(encoding="utf-8") == ts)
        if not ok:
            print("生成物与 schema 不一致，请运行 gen.py 重新生成")
            return 1
        print("contracts 生成物一致 ✓")
        return 0
    OUT_PY.parent.mkdir(parents=True, exist_ok=True)
    OUT_TS.parent.mkdir(parents=True, exist_ok=True)
    OUT_PY.write_text(py, encoding="utf-8")
    OUT_TS.write_text(ts, encoding="utf-8")
    print(f"生成 {OUT_PY}\n生成 {OUT_TS}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
